/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientSide;

import java.awt.HeadlessException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sunil
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    String username;
    String who;
    String Lname, Laccount, Ldob, Ldateofcreation, Laadhar, LMobile, Lbalance, Ltype;
    int Lpincode;

    public Customer() {
        initComponents();
    }

    public Customer(String username, String who) {
        initComponents();
        this.username = username;
        this.who = who;
        this.user.setText(username);
        ClientStub client = new ClientStub();
        try {
            Laccount = client.stub.getAccountnoByusername(username);
            if (!Laccount.equals("")) {
//                JOptionPane.showMessageDialog(this,"Login successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Login Failed.");
                this.setVisible(false);
                login l = new login();
                l.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("in constructor at Customer." + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transfer = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        checkbalance = new javax.swing.JButton();
        passbook = new javax.swing.JButton();
        seeprofile = new javax.swing.JButton();
        deleteaccount = new javax.swing.JButton();
        checkemail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transfer.setText("Transfer");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        checkbalance.setText("Check Balance");
        checkbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbalanceActionPerformed(evt);
            }
        });

        passbook.setText("Passbook");
        passbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passbookActionPerformed(evt);
            }
        });

        seeprofile.setText("See Profile");
        seeprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeprofileActionPerformed(evt);
            }
        });

        deleteaccount.setText("Delete Account");
        deleteaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteaccountActionPerformed(evt);
            }
        });

        checkemail.setText("Chech Email");
        checkemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(checkbalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transfer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(passbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seeprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transfer)
                    .addComponent(passbook))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbalance)
                    .addComponent(seeprofile))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkemail)
                    .addComponent(deleteaccount))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void checkbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbalanceActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CheckBalance c;
        c = new CheckBalance(this.username, who);
        c.setTextofAccount(Laccount);
        c.setVisible(true);
    }//GEN-LAST:event_checkbalanceActionPerformed

    private void passbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passbookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SeeTransection s;
        s = new SeeTransection(this.username, who);
        s.setTextofAccount(Laccount);
        s.setVisible(true);
    }//GEN-LAST:event_passbookActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        Transfer t;
        t = new Transfer(this.username, who);
        t.setTextofAccount(Laccount);
        t.setVisible(true);
    }//GEN-LAST:event_transferActionPerformed

    private void seeprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeprofileActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        SeeProfile s;
        s = new SeeProfile(this.username, who);
        s.setTextofAccount(Laccount);
        s.setVisible(true);
    }//GEN-LAST:event_seeprofileActionPerformed

    private void deleteaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteaccountActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        DeleteAccount d;
        d = new DeleteAccount(this.username, who);
        d.setTextofAccount(Laccount);
        d.setVisible(true);
    }//GEN-LAST:event_deleteaccountActionPerformed

    private void checkemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkemailActionPerformed
        // TODO add your handling code here:

        ClientStub client = new ClientStub();
        try {
            String email = client.stub.getEmailAddressByusername(this.username);
            String subject = null,body = null;
            JOptionPane.showMessageDialog(this, email);
            SendEmail em=new SendEmail();
            try {
                boolean result = em.sendEmail(email,subject,body);
            } catch (Exception ex) {
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (RemoteException ex) {
            System.out.println("At check email at customer.java" + ex);
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_checkemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Customer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkbalance;
    private javax.swing.JButton checkemail;
    private javax.swing.JButton deleteaccount;
    private javax.swing.JButton logout;
    private javax.swing.JButton passbook;
    private javax.swing.JButton seeprofile;
    private javax.swing.JButton transfer;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
